### ISSUE TITLE
Call me obnoxious

### ISSUE THREAD

**Issue by DBJDBJ** [bstamour/units#1]
But I might think I have stumbled upon equally functional concept, but much simpler implementation. 

I slightly  expanded on it [here](https://dbj.org/c-strong-duck/) ...

**Comment by bstamour** [comment]
Sorry about the delay in responding. I think it's great that there are many different implementations of units for C++. There's even movement on the ISO committee around the topic!

**Comment by DBJDBJ** [comment]
Many thanks for a comment. I would like to focus the audience, "my" solution is C and C++ friendly. 
It is not mine at all, it is based on the "strong type" concept.  Amount of code to implement it is almost zero.

Kind regards ...

**Comment by bstamour** [comment]
Sounds good. I think I'll close this issue now though, since it's not really an issue. If you'd like to discuss the idea more, feel free to send me an email. bryan@bryanstamour.com
